name: 'GitHub Tag'
description: 'Publish GitHub tags from a push action'
inputs: 
  tag:
    description: The git tag name.
    required: true
  message: 
    description: The message for the git tag.
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.message }}
